# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=20)),
                ('productimg', models.CharField(max_length=200)),
                ('productname', models.CharField(max_length=100)),
                ('productlongname', models.CharField(max_length=100)),
                ('isxf', models.NullBooleanField(default=False)),
                ('pmdesc', models.NullBooleanField(default=False)),
                ('specifics', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('marketprice', models.CharField(max_length=50)),
                ('categoryid', models.CharField(max_length=20)),
                ('childcid', models.CharField(max_length=20)),
                ('childcidname', models.CharField(max_length=100)),
                ('dealerid', models.CharField(max_length=20)),
                ('storenums', models.CharField(max_length=20)),
                ('productnum', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
